# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates: 
- package-ecosystem: npm
  directory: "/"
  pull-request-branch-name:
    separator: "/"
  schedule:
    interval: monthly
    day: monday
    time: "10:00"
    timezone: Europe/Madrid
  labels:
  - "npm"
  - "dependencies"
  reviewers:
  - macalbert
  assignees:
  - macalbert
    
- package-ecosystem: github-actions
  directory: "/"
  pull-request-branch-name:
      separator: "/"
  schedule:
    interval: monthly
    day: monday
    time: "10:00"
    timezone: Europe/Madrid
  labels:
  - "github-actions"
  - "dependencies"
  reviewers:
  - macalbert
  assignees:
  - macalbert